# Generated by Django 4.2.1 on 2023-05-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies_table',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=400)),
                ('company_type', models.CharField(max_length=400)),
                ('company_owner', models.CharField(max_length=250)),
                ('company_address', models.CharField(max_length=400)),
                ('company_phone', models.CharField(max_length=100, unique=True)),
                ('company_total_employees', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employees_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='email')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=90, verbose_name='first name')),
                ('last_name', models.CharField(max_length=90, verbose_name='last name')),
                ('date_of_birth', models.CharField(blank=True, max_length=350)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('profile_pic_thumbnail', models.ImageField(upload_to='profile_thumbnails')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('fk_company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_id', to='website.companies_table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
